#pragma once
#define VIRTUALKD_VERSION 		 3,0,0,1
#define VIRTUALKD_VERSION_STR 	"3.0"
#define COPYRIGHT_STR			"LGPL"
#define TRADEMARKS_STR			"VirtualKD"
#define PRODUCTNAME_STR			"VirtualKD"
#define COMPANY_STR				"Sysprogs OU"
#define COMMENTS_STR			"http://virtualkd.sysprogs.org/"
#define VIRTUALKD_VER_INT		0x03000000

#define KDCLIENT_DLL_VER_STR	VIRTUALKD_VERSION_STR
#define KDCLIENT_DLL_VER		VIRTUALKD_VERSION

#define VMXPATCH_EXE_VER_STR	VIRTUALKD_VERSION_STR
#define VMXPATCH_EXE_VER		VIRTUALKD_VERSION

#define VMMON_EXE_VER_STR		VIRTUALKD_VERSION_STR
#define VMMON_EXE_VER			VIRTUALKD_VERSION

#define VMINSTALL_EXE_VER_STR	VIRTUALKD_VERSION_STR
#define VMINSTALL_EXE_VER		VIRTUALKD_VERSION

#define KERNEL_PART_VER			3,0,0,1
#define KERNEL_PART_VER_STR		"3.0"

#define KDPATCH_SYS_VER_STR		KERNEL_PART_VER_STR
#define KDPATCH_SYS_VER			KERNEL_PART_VER

#define KDVM_DLL_VER_STR		KERNEL_PART_VER_STR
#define KDVM_DLL_VER			KERNEL_PART_VER
